// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Connect(arg1:string,arg2:number,arg3:number):Promise<void>;

export function Disconnect():Promise<void>;

export function Read(arg1:string,arg2:number,arg3:number):Promise<Array<main.modbusData>>;

export function SetConnected(arg1:boolean):Promise<void>;
