// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Connect(arg1, arg2, arg3) {
  return window['go']['main']['App']['Connect'](arg1, arg2, arg3);
}

export function Disconnect() {
  return window['go']['main']['App']['Disconnect']();
}

export function Read(arg1, arg2, arg3) {
  return window['go']['main']['App']['Read'](arg1, arg2, arg3);
}

export function SetConnected(arg1) {
  return window['go']['main']['App']['SetConnected'](arg1);
}

export function Write(arg1, arg2, arg3) {
  return window['go']['main']['App']['Write'](arg1, arg2, arg3);
}
