name: Wails build

on:
  push:
    tags:
      - "*"
env:
  # Necessary for most environments as build failure can occur due to OOM issues
  NODE_OPTIONS: "--max-old-space-size=4096"

jobs:
  build:
    strategy:
      # Failure in one platform build won't impact the others
      fail-fast: false
      matrix:
        build:
          - name: "ModbusExplorer-ubuntu22"
            platform: "linux/amd64"
            os: "ubuntu-latest"
          - name: "ModbusExplorer.exe"
            platform: "windows/amd64"
            os: "windows-latest"
          # - name: 'App'
          #   platform:  'darwin/universal'
          #   os: 'macos-latest'

    runs-on: ${{ matrix.build.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Build wails
        uses: dAppServer/wails-build-action@v2.2
        id: build
        with:
          build-name: ${{ matrix.build.name }}
          build-platform: ${{ matrix.build.platform }}
          package: true
          go-version: "1.22"
          node-version: "20"
  build-linux-2404:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.22"
      - name: Install Wails
        run: go install github.com/wailsapp/wails/v2/cmd/wails@latest

      - name: Install Wails dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.1-dev

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"
      - name: Build Wails application
        run: wails build -tags webkit2_41 -o ModbusExplorer-ubuntu24

      - name: Add Linux perms
        working-directory: .
        run: chmod +x build/bin/*
        shell: bash
      - uses: actions/upload-artifact@v3
        with:
          name: Wails Build ${{runner.os}} ${{inputs.build-name}}
          path: |
            */bin/
            *\bin\*
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            */bin/*
